_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: torch.load
    f: ${enc_path1} #for view 1
  - _target_: torch.load
    f: ${enc_path2} #for view 2
normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 1024
