views: 2
action_dim: 2

workspace:
  _target_: workspaces.block_push_multiview.BlockPushMultiviewWorkspace

dataset:
  _target_: datasets.block_pushing.PushMultiviewTrajectoryDataset
  data_directory: ${env_vars.datasets.block_push}
  onehot_goals: False
  subset_fraction: ${subset_fraction}
  prefetch: True

transform:
  _target_: datasets.transform.custom_transform
  random_resized_crop: false
  color_jitter: false
  random_grayscale: false
  gaussian_blur: false
  horizontal_flip: false