views: 1
action_dim: 2

workspace:
  _target_: workspaces.pusht.PushTWorkspace

dataset:
  _target_: datasets.pusht.PushTDataset
  data_directory: ${env_vars.datasets.pusht}
  subset_fraction: ${subset_fraction}
  relative: ${relative}

transform:
  _target_: datasets.transform.custom_transform
  random_resized_crop: false
  color_jitter: false
  random_grayscale: false
  gaussian_blur: false
  horizontal_flip: false