_target_: models.encoder.resnet.resnet18
pretrained: False
output_dim: 512
unit_norm: False
# mean: [0.485, 0.456, 0.406] #imgnet
# std: [0.229, 0.224, 0.225] #imgnet

mean: [0.4583, 0.5643, 0.8529] # normal for kitchen
std: [0.1479, 0.3041, 0.07]  # normal for kitchen